export type Movie = {
  title: string;
  od: string;
  vote_average: number;
  poster_path: string;
  backdrop_path: string;
  id: number;
  overview: string;
  runtime: string;
  genres: [];
  popularity: number;
  release_date: string;
  adult: false;
  vote_count: number;
  credits: string;
  department: string;
  crew: string;
  name: string;
  cast: string;
  known_for_department: string;
};
